# Generated by Django 5.2.7 on 2026-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
