# Generated by Django 5.2.7 on 2026-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_profile_avatar_requested_at_profile_pending_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
