# Generated by Django 5.2.7 on 2026-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_playlist_video_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlists',
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
