# Generated by Django 5.2.7 on 2026-01-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_video_is_hidden_remove_video_playlists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='created_at',
        ),
    ]
