# Generated by Django 5.2.7 on 2026-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_rename_uploaded_at_video_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
