# Generated by Django 5.2.7 on 2026-02-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_is_private_video_thumbnail_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.AddField(
            model_name='video',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
