# Generated by Django 5.2.7 on 2026-02-06 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_video_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='creator',
            new_name='channel',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together={('user', 'video')},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='created_at',
        ),
    ]
