# Generated by Django 5.2.10 on 2026-02-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_alter_subscription_unique_together_and_more'),
        ('videos', '0018_playlist_is_public_notification'),
    ]

    operations = [
    ]
